# Specify workflow name
name: Build and Push Docker image

# Setup a trigger. In this case trigger for pushing to main branch
on:
  push:
    branches: ["main"]

# Describe jobs
jobs: 
  build-and-push:
    # Choose an image
    runs-on: ubuntu-latest

  # Permissions for GitHub token
    permissions:
      contents: read
      packages: write

    steps:
      # Download all codes to our virtual machine
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          lowercase: true
